if (isDedicated) exitwith {};
_Targets = _this select 3;
switch (_Targets) do
{
     case "Compound 1": {
	     
	     	hint Format ["Compound 1: Reseting Targets.."];
	     	sleep 1;
	      Compound1_target1 animate ["terc", 1];
		Compound1_target2 animate ["terc", 1];
		Compound1_target3 animate ["terc", 1];
		Compound1_target4 animate ["terc", 1];
		Compound1_target5 animate ["terc", 1];
		Compound1_target6 animate ["terc", 1];
		Compound1_target7 animate ["terc", 1];
		hint Format ["Compound 1: Targets Raised."];
		sleep 1;
		Compound1_target1 animate ["terc", 0];
		Compound1_target2 animate ["terc", 0];
		Compound1_target3 animate ["terc", 0];
		Compound1_target4 animate ["terc", 0];
		Compound1_target5 animate ["terc", 0];
		Compound1_target6 animate ["terc", 0];
		Compound1_target7 animate ["terc", 0];
		sleep 2;
		Compound1_target7 animate ["terc", 0];
		hint Format ["Compound 1: Targets Complete."];};
	     
     case "Compound 2": {
	     
	     	hint Format ["Compound 2: Targets Being Raised."];
	     	sleep 2;
	      Compound2_target1 animate ["terc", 1];
		Compound2_target2 animate ["terc", 1];
		Compound2_target3 animate ["terc", 1];
		Compound2_target4 animate ["terc", 1];
		Compound2_target5 animate ["terc", 1];
		Compound2_target6 animate ["terc", 1];
		Compound2_target7 animate ["terc", 1];
		Compound2_target8 animate ["terc", 1];
		Compound2_target9 animate ["terc", 1];
		Compound2_target10 animate ["terc", 1];
	     	hint Format ["Compound 2: Targets Raised."];
		Compound2_target1 animate ["terc", 0];
		Compound2_target2 animate ["terc", 0];
		Compound2_target3 animate ["terc", 0];
		Compound2_target4 animate ["terc", 0];
		Compound2_target5 animate ["terc", 0];
		Compound2_target6 animate ["terc", 0];
		Compound2_target7 animate ["terc", 0];
		Compound2_target8 animate ["terc", 0];
		sleep 8;
		Compound2_target9 animate ["terc", 0];
		Compound2_target10 animate ["terc", 0];
		sleep 2;
		Compound2_target11 animate ["terc", 0];
		sleep 2;
		Compound2_target12 animate ["terc", 0];
		
		sleep 2;
		hint Format ["Compound 2: Live."];};      

     case "BOBC": {
	     	
	     
	     	hint Format ["Bounding Overwatch I: Reseting Targets."];
	      BOBC_T2 animate ["terc", 1];
		BOBC_T6 animate ["terc", 1];
		BOBC_T1 animate ["terc", 1];
		BOBC_T3 animate ["terc", 1];
		BOBC_T4 animate ["terc", 1];
		BOBC_T5 animate ["terc", 1];
		BOBC_T7 animate ["terc", 1];
		BOBC_T8 animate ["terc", 1];
		BOBC_T9 animate ["terc", 1];
		BOBC_T10 animate ["terc", 1];
		BOBC_T11 animate ["terc", 1];
		sleep 2;
	     	hint Format ["Bounding Overwatch I: 10 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 9 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 8 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 7 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 6 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 5 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 4 Seconds."];
	      Sleep 1;
	     	hint Format ["Bounding Overwatch I: 3 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 2 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch I: 1 Seconds."];
	      Sleep 1;
		BOBC_T2 animate ["terc", 0];
		Sleep 6;
		BOBC_T6 animate ["terc", 0];
		BOBC_T1 animate ["terc", 0];
		Sleep 10;
		BOBC_T3 animate ["terc", 0];
		BOBC_T4 animate ["terc", 0];
		Sleep 5;
		BOBC_T5 animate ["terc", 0];
		Sleep 12;
		BOBC_T8 animate ["terc", 0];
		BOBC_T7 animate ["terc", 0];
		BOBC_T9 animate ["terc", 0];
		sleep 10;
		BOBC_T11 animate ["terc", 0];
		BOBC_T10 animate ["terc", 0];
		Sleep 3;
		hint Format ["Bounding Overwatch I: Finished."];};  
		  
     case "Compound 3": {
	     
	     	hint Format ["Compound 3: Reseting Targets.."];
	     	sleep 1;
	      Compound3_target1 animate ["terc", 1];
		Compound3_target2 animate ["terc", 1];
		Compound3_target3 animate ["terc", 1];
		Compound3_target4 animate ["terc", 1];
		Compound3_target5 animate ["terc", 1];
		Compound3_target6 animate ["terc", 1];
		Compound3_target7 animate ["terc", 1];
		Compound3_target8 animate ["terc", 1];
		Compound3_target9 animate ["terc", 1];
		hint Format ["Compound 3: Targets Raised."];
		sleep 1;
		Compound3_target1 animate ["terc", 0];
		Compound3_target2 animate ["terc", 0];
		Compound3_target3 animate ["terc", 0];
		Compound3_target4 animate ["terc", 0];
		Compound3_target5 animate ["terc", 0];
		Compound3_target6 animate ["terc", 0];
		Compound3_target7 animate ["terc", 0];
		Compound3_target8 animate ["terc", 0];
		Compound3_target9 animate ["terc", 0];
		sleep 2;
		hint Format ["Compound 3: Targets Complete."];};
	     
     case "Compound 4": {
	     
	     	hint Format ["Compound 4: Targets Being Raised."];
	     	sleep 2;
	      Compound4_target1 animate ["terc", 1];
		Compound4_target2 animate ["terc", 1];
		Compound4_target3 animate ["terc", 1];
		Compound4_target4 animate ["terc", 1];
		Compound4_target5 animate ["terc", 1];
		Compound4_target6 animate ["terc", 1];
		Compound4_target7 animate ["terc", 1];
		Compound4_target8 animate ["terc", 1];
		Compound4_target9 animate ["terc", 1];
		Compound4_target10 animate ["terc", 1];
	     	hint Format ["Compound 2: Targets Raised."];
		Compound4_target1 animate ["terc", 0];
		Compound4_target2 animate ["terc", 0];
		Compound4_target3 animate ["terc", 0];
		Compound4_target4 animate ["terc", 0];
		Compound4_target5 animate ["terc", 0];
		Compound4_target6 animate ["terc", 0];
		Compound4_target7 animate ["terc", 0];
		Compound4_target8 animate ["terc", 0];
		sleep 2;
		hint Format ["Compound 4: Live."];   
		sleep 8;
		Compound4_target9 animate ["terc", 0];
		Compound4_target10 animate ["terc", 0];
		sleep 2;
		Compound4_target11 animate ["terc", 0]; 
		sleep 2;
		hint Format ["Compound 4: Targets Finished"];};   

     case "BOBC2": {
	     	
	     	hint Format ["Bounding Overwatch II: Reseting Targets."];
	      BOBC2_T2 animate ["terc", 1];
		BOBC2_T6 animate ["terc", 1];
		BOBC2_T1 animate ["terc", 1];
		BOBC2_T3 animate ["terc", 1];
		BOBC2_T4 animate ["terc", 1];
		BOBC2_T5 animate ["terc", 1];
		BOBC2_T7 animate ["terc", 1];
		BOBC2_T8 animate ["terc", 1];
		BOBC2_T9 animate ["terc", 1];
		BOBC2_T10 animate ["terc", 1];
		BOBC2_T11 animate ["terc", 1];
		BOBC2_T12 animate ["terc", 1];
		sleep 2;
	     	hint Format ["Bounding Overwatch II: 10 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 9 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 8 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 7 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 6 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 5 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 4 Seconds."];
	      Sleep 1;
	     	hint Format ["Bounding Overwatch II: 3 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 2 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: 1 Seconds."];
	      Sleep 1;
	      hint Format ["Bounding Overwatch II: Live."];
		BOBC2_T1 animate ["terc", 0];
		BOBC2_T2 animate ["terc", 0];
		Sleep 6;
		BOBC2_T3 animate ["terc", 0];
		BOBC2_T4 animate ["terc", 0];
		Sleep 10;
		BOBC2_T6 animate ["terc", 0];
		BOBC2_T7 animate ["terc", 0];
		Sleep 5;
		BOBC2_T5 animate ["terc", 0];
		Sleep 12;
		BOBC2_T8 animate ["terc", 0];
		BOBC2_T11 animate ["terc", 0];
		sleep 5;
		BOBC2_T9 animate ["terc", 0];
		BOBC2_T10 animate ["terc", 0];
		Sleep 10;
		BOBC2_T12 animate ["terc", 0];
		hint Format ["Bounding Overwatch II: Finished."];};      
	     };
};
